<a href="https://colab.research.google.com/github/zydusss/PyTorch/blob/main/Tensors_101.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
! pip3 install torch

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [20]:
import torch
import numpy as np

Tensors - generalization of matrices with n dimensions. Could be 0,1,2,..n dimensional

Let's create 1 dimensional tensor!

In [7]:
t1 = torch.tensor([1,2,3,4,5,6])
print(t1)

tensor([1, 2, 3, 4, 5, 6])


In [8]:
print(t1[2])

tensor(3)


In [10]:
print(t1[1:3])

tensor([2, 3])


In [11]:
ft1 = torch.FloatTensor([1,2,3,4,5,6])
print(ft1)

tensor([1., 2., 3., 4., 5., 6.])


In [12]:
print(ft1.dtype)

torch.float32


In [14]:
print(ft1.size())

torch.Size([6])


In [17]:
t1.view(6,1) # Similiar to reshape

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [18]:
t1.view(2,-1)

tensor([[1, 2, 3],
        [4, 5, 6]])

Numpy to Tensor Conversion

In [21]:
a = np.array([1,2,3,4,5])

In [23]:
tensor_csv = torch.from_numpy(a)
print(tensor_csv.type())
print(tensor_csv)

torch.LongTensor
tensor([1, 2, 3, 4, 5])


Tensor to Numpy conversion

In [26]:
np_arr = tensor_csv.numpy()
print(np_arr.dtype)
print(np_arr)

int64
[1 2 3 4 5]
